### PR TITLE
Automatic version update to v2.5.2

### PR DESCRIPTION
**Pull request by GiovanH**

### CODE REVIEW

**Comment by GiovanH** [comment]
Not sure what's happening here.

**Comment by Grafcube** [comment]
I'm not at my desktop so I can't push any fixes, but I can leave the steps here.

1. Update the appstream metadata in the source repo.

2. Update the manifest here to use the commit with the updated metadata.

   ```yaml
   # Required for icons, desktop file and appstream file 
   - type: git 
     url: https://github.com/GiovanH/unofficial-homestuck-collection.git
     commit: "5620e9cfc7df008958267eafe71c2d68c4cb2305" # change this
   ```

3. Install the test build and if it works correctly, merge the PR. The build will be queued to be published.

Let me know if you need any help!

**Comment by GiovanH** [comment]
I think everything is set properly, except that the metadata in the source repo on the release commit doesn't have info for the github release (how can it, it doesn't know its own hash). What's weird is the build isn't running.

**Comment by Grafcube** [comment]
> the metadata in the source repo on the release commit doesn't have info for the github release

Yes. That's why I added a separate git source in the manifest specifically to pull the latest metadata. That way it's fine even if the release doesn't have the up to date appstream.

> What's weird is the build isn't running.

It seems to have run [here](https://buildbot.flathub.org/#/builders/6/builds/151231). You should be able to see why it failed on the link. Unfortunately the site seems to be really bad on mobile so I don't know why the build failed.

**Comment by GiovanH** [comment]
I'm looking at 151231 now, but [150918](https://buildbot.flathub.org/#/builders/6/builds/150918) definitely never ran.

**Comment by GiovanH** [comment]
Looks like `sha="$(curl $tarurl | sha256sum | cut -d' ' -f1)"` somehow isn't generating the right hash.

**Pull request merged**
